openapi: '3.0.2'

info:
  title: API spec for testing
  version: '1.0'

servers:
  - url: http://localhost/api

paths:
  /echo:
    get:
      operationId: test_handler.show
      parameters:
        - name: message
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: |
            Success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
