openapi: '3.0.2'

info:
  title: rezept-db backend API
  version: '1.0'

servers:
  - url: http://localhost:9000/api
    description: |
      Local development server.
  - url: http://aragorn.shire.grandrath-net.de/api
    description: |
      Production server.

paths:
  /health:
    get:
      description: |
        Reports system health.
      operationId: health.show
      responses:
        '200':
          description: |
            The system is up and running.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemStatus'

  /recipes:
    get:
      description: |
        Get a list of recipes.
      operationId: recipes.index
      parameters:
        - in: query
          name: name
          schema:
            type: string
            example: pizza
          required: false
          allowEmptyValue: true
          description: |
            If present only recipes that contain the given string in their
            `name` will be returned.
      responses:
        '200':
          description: |
            OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipes:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipe'
                required:
                  - recipes

    post:
      description: |
        Create a new recipe entry.
      operationId: recipes.create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeInput'
      responses:
        '201':
          description: |
            The recipe has been created.
          headers:
            Location:
              description: |
                The recipe's URL.
              schema:
                type: string
                format: uri
                example: https://example.com/recipes/recipe-123

components:
  schemas:
    RecipeInput:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/RecipeName'
        notes:
          $ref: '#/components/schemas/RecipeNotes'
      required:
        - name

    Recipe:
      type: object
      properties:
        recipeId:
          $ref: '#/components/schemas/RecipeId'
        name:
          $ref: '#/components/schemas/RecipeName'
        notes:
          $ref: '#/components/schemas/RecipeNotes'
      required:
        - recipeId

    RecipeId:
      type: string
      description: |
        The recipe's unique id.
      example: 257066a2-a1d7-4bed-a4f8-97b54bc88efb

    RecipeName:
      type: string
      minLength: 1
      description: |
        Descriptive name.
      example: Grilled cheese

    RecipeNotes:
      type: string
      nullable: true
      description: |
        Arbitrary notes.
      example: American cheese melts best

    SystemStatus:
      type: object
      properties:
        status:
          type: string
          description: |
            "OK" if system is healthy, an error message otherwise.
          example: OK
      required:
        - status
